hoistPattern:
  - '*'
hoistedDependencies:
  /@babel/code-frame/7.22.13:
    '@babel/code-frame': private
  /@babel/helper-validator-identifier/7.22.5:
    '@babel/helper-validator-identifier': private
  /@babel/highlight/7.22.13:
    '@babel/highlight': private
  /@cspotcode/source-map-support/0.8.1:
    '@cspotcode/source-map-support': private
  /@jridgewell/resolve-uri/3.1.1:
    '@jridgewell/resolve-uri': private
  /@jridgewell/sourcemap-codec/1.4.15:
    '@jridgewell/sourcemap-codec': private
  /@jridgewell/trace-mapping/0.3.9:
    '@jridgewell/trace-mapping': private
  /@puppeteer/browsers/1.4.6(typescript@5.2.2):
    '@puppeteer/browsers': private
  /@sentry-internal/tracing/7.66.0:
    '@sentry-internal/tracing': private
  /@sentry/browser/7.66.0:
    '@sentry/browser': private
  /@sentry/core/7.66.0:
    '@sentry/core': private
  /@sentry/replay/7.66.0:
    '@sentry/replay': private
  /@sentry/types/7.66.0:
    '@sentry/types': private
  /@sentry/utils/7.66.0:
    '@sentry/utils': private
  /@tootallnate/quickjs-emscripten/0.23.0:
    '@tootallnate/quickjs-emscripten': private
  /@tsconfig/node10/1.0.9:
    '@tsconfig/node10': private
  /@tsconfig/node12/1.0.11:
    '@tsconfig/node12': private
  /@tsconfig/node14/1.0.3:
    '@tsconfig/node14': private
  /@tsconfig/node16/1.0.4:
    '@tsconfig/node16': private
  /@types/node/20.5.7:
    '@types/node': private
  /@types/yauzl/2.10.0:
    '@types/yauzl': private
  /acorn-walk/8.2.0:
    acorn-walk: private
  /acorn/8.10.0:
    acorn: private
  /agent-base/7.1.0:
    agent-base: private
  /ansi-regex/5.0.1:
    ansi-regex: private
  /ansi-styles/3.2.1:
    ansi-styles: private
  /arg/4.1.3:
    arg: private
  /argparse/2.0.1:
    argparse: private
  /ast-types/0.13.4:
    ast-types: private
  /b4a/1.6.4:
    b4a: private
  /base64-js/1.5.1:
    base64-js: private
  /basic-ftp/5.0.3:
    basic-ftp: private
  /bezier-easing/2.1.0:
    bezier-easing: private
  /buffer-crc32/0.2.13:
    buffer-crc32: private
  /buffer/5.7.1:
    buffer: private
  /call-bind/1.0.2:
    call-bind: private
  /callsites/3.1.0:
    callsites: private
  /chalk/2.4.2:
    chalk: private
  /chromium-bidi/0.4.16(devtools-protocol@0.0.1147663):
    chromium-bidi: private
  /cliui/8.0.1:
    cliui: private
  /color-convert/1.9.3:
    color-convert: private
  /color-name/1.1.3:
    color-name: private
  /cosmiconfig/8.2.0:
    cosmiconfig: private
  /create-require/1.1.1:
    create-require: private
  /cross-fetch/4.0.0:
    cross-fetch: private
  /data-uri-to-buffer/5.0.1:
    data-uri-to-buffer: private
  /debug/4.3.4:
    debug: private
  /degenerator/5.0.1:
    degenerator: private
  /devtools-protocol/0.0.1147663:
    devtools-protocol: private
  /diff/4.0.2:
    diff: private
  /emoji-regex/8.0.0:
    emoji-regex: private
  /end-of-stream/1.4.4:
    end-of-stream: private
  /error-ex/1.3.2:
    error-ex: private
  /escalade/3.1.1:
    escalade: private
  /escape-string-regexp/1.0.5:
    escape-string-regexp: private
  /escodegen/2.1.0:
    escodegen: private
  /esprima/4.0.1:
    esprima: private
  /estraverse/5.3.0:
    estraverse: private
  /esutils/2.0.3:
    esutils: private
  /extract-zip/2.0.1:
    extract-zip: private
  /fast-fifo/1.3.2:
    fast-fifo: private
  /fd-slicer/1.1.0:
    fd-slicer: private
  /fs-extra/8.1.0:
    fs-extra: private
  /function-bind/1.1.1:
    function-bind: private
  /get-caller-file/2.0.5:
    get-caller-file: private
  /get-intrinsic/1.2.1:
    get-intrinsic: private
  /get-stream/5.2.0:
    get-stream: private
  /get-uri/6.0.1:
    get-uri: private
  /graceful-fs/4.2.11:
    graceful-fs: private
  /has-flag/3.0.0:
    has-flag: private
  /has-proto/1.0.1:
    has-proto: private
  /has-symbols/1.0.3:
    has-symbols: private
  /has/1.0.3:
    has: private
  /http-proxy-agent/7.0.0:
    http-proxy-agent: private
  /https-proxy-agent/7.0.1:
    https-proxy-agent: private
  /ieee754/1.2.1:
    ieee754: private
  /import-fresh/3.3.0:
    import-fresh: private
  /ip/1.1.8:
    ip: private
  /is-arrayish/0.2.1:
    is-arrayish: private
  /is-fullwidth-code-point/3.0.0:
    is-fullwidth-code-point: private
  /isarray/0.0.1:
    isarray: private
  /js-cookie/2.2.1:
    js-cookie: private
  /js-tokens/4.0.0:
    js-tokens: private
  /js-yaml/4.1.0:
    js-yaml: private
  /json-parse-even-better-errors/2.3.1:
    json-parse-even-better-errors: private
  /jsonfile/4.0.0:
    jsonfile: private
  /lines-and-columns/1.2.4:
    lines-and-columns: private
  /lru-cache/7.18.3:
    lru-cache: private
  /make-error/1.3.6:
    make-error: private
  /mitt/3.0.0:
    mitt: private
  /mkdirp-classic/0.5.3:
    mkdirp-classic: private
  /ms/2.1.2:
    ms: private
  /netmask/2.0.2:
    netmask: private
  /node-fetch/2.7.0:
    node-fetch: private
  /object-inspect/1.12.3:
    object-inspect: private
  /once/1.4.0:
    once: private
  /pac-proxy-agent/7.0.0:
    pac-proxy-agent: private
  /pac-resolver/7.0.0:
    pac-resolver: private
  /parent-module/1.0.1:
    parent-module: private
  /parse-json/5.2.0:
    parse-json: private
  /path-to-regexp/1.8.0:
    path-to-regexp: private
  /path-type/4.0.0:
    path-type: private
  /pend/1.2.0:
    pend: private
  /progress/2.0.3:
    progress: private
  /proxy-agent/6.3.0:
    proxy-agent: private
  /proxy-from-env/1.1.0:
    proxy-from-env: private
  /pump/3.0.0:
    pump: private
  /punycode/2.3.0:
    punycode: private
  /puppeteer-core/20.9.0(typescript@5.2.2):
    puppeteer-core: private
  /puppeteer/20.9.0(typescript@5.2.2):
    puppeteer: private
  /qs/6.11.2:
    qs: private
  /queue-tick/1.0.1:
    queue-tick: private
  /require-directory/2.1.1:
    require-directory: private
  /resolve-from/4.0.0:
    resolve-from: private
  /rxjs/7.8.1:
    rxjs: private
  /side-channel/1.0.4:
    side-channel: private
  /smart-buffer/4.2.0:
    smart-buffer: private
  /socks-proxy-agent/8.0.1:
    socks-proxy-agent: private
  /socks/2.7.1:
    socks: private
  /source-map/0.6.1:
    source-map: private
  /streamx/2.15.1:
    streamx: private
  /string-width/4.2.3:
    string-width: private
  /strip-ansi/6.0.1:
    strip-ansi: private
  /supports-color/5.5.0:
    supports-color: private
  /tar-fs/3.0.4:
    tar-fs: private
  /tar-stream/3.1.6:
    tar-stream: private
  /through/2.3.8:
    through: private
  /tr46/0.0.3:
    tr46: private
  /ts-node/10.9.1(@types/node@20.5.7)(typescript@5.2.2):
    ts-node: private
  /tslib/2.6.2:
    tslib: private
  /typescript/5.2.2:
    typescript: private
  /unbzip2-stream/1.4.3:
    unbzip2-stream: private
  /universalify/0.1.2:
    universalify: private
  /v8-compile-cache-lib/3.0.1:
    v8-compile-cache-lib: private
  /vue-scrollto/2.20.0:
    vue-scrollto: private
  /webidl-conversions/3.0.1:
    webidl-conversions: private
  /weixin-js-sdk/1.6.0:
    weixin-js-sdk: private
  /whatwg-url/5.0.0:
    whatwg-url: private
  /wrap-ansi/7.0.0:
    wrap-ansi: private
  /wrappy/1.0.2:
    wrappy: private
  /ws/8.13.0:
    ws: private
  /y18n/5.0.8:
    y18n: private
  /yargs-parser/21.1.1:
    yargs-parser: private
  /yargs/17.7.1:
    yargs: private
  /yauzl/2.10.0:
    yauzl: private
  /yn/3.1.1:
    yn: private
included:
  dependencies: true
  devDependencies: true
  optionalDependencies: true
injectedDeps: {}
layoutVersion: 5
nodeLinker: isolated
packageManager: pnpm@8.7.1
pendingBuilds: []
prunedAt: Fri, 01 Sep 2023 08:12:21 GMT
publicHoistPattern:
  - '*eslint*'
  - '*prettier*'
registries:
  '@other-registry': https://nexus.other.com/repository/npm-registry/
  default: https://mirrors.cloud.tencent.com/npm/
skipped: []
storeDir: /Users/other/Library/pnpm/store/v3
virtualStoreDir: .pnpm
